rvm:
  - 1.9.3
  - 1.8.7
  - 1.9.2
env:
  - DOORKEEPER_ORM=active_record
  - DOORKEEPER_ORM=mongoid
  - DOORKEEPER_ORM=mongo_mapper
gemfile:
  - gemfiles/gemfile.rails-3.1.x
  - gemfiles/gemfile.rails-3.2.x
services:
  - mongodb
matrix:
  exclude:
    - rvm: 1.8.7
      env: DOORKEEPER_ORM=mongoid
      gemfile: gemfiles/gemfile.rails-3.1.x
    - rvm: 1.8.7
      env: DOORKEEPER_ORM=mongoid
      gemfile: gemfiles/gemfile.rails-3.2.x
    - rvm: 1.9.2
      env: DOORKEEPER_ORM=mongoid
      gemfile: gemfiles/gemfile.rails-3.1.x
    - rvm: 1.9.2
      env: DOORKEEPER_ORM=mongoid
      gemfile: gemfiles/gemfile.rails-3.2.x
